[workspace]
members = ["crates/session-core", "crates/session-protocol"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
ed25519-dalek = { version = "=3.0.0", default-features = false, features = ["fast", "zeroize"] }
minicbor = { version = "=2.3.0", features = ["std"] }
thiserror = "=2.0.20"
zeroize = { version = "=1.9.0", default-features = false, features = ["alloc"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
