version: '3.7'
services:
  nginx-base:
    image: nginx:1.19-alpine
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./certs/:/etc/nginx/ssl
  redis-base:
    image: redis:alpine
    hostname: redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    restart: always
  url-shortner-base:
    image: shlinkio/shlink:stable
    ports:
      - '${SHORT_DOMAIN_PORT}:${SHORT_DOMAIN_PORT}'
    environment:
      - SHORT_DOMAIN_HOST=${SHORT_DOMAIN_HOST}
      - SHORT_DOMAIN_SCHEMA=${SHORT_DOMAIN_SCHEMA}
      - GEOLITE_LICENSE_KEY=${GEOLITE_LICENSE_KEY}
