version: '3.7'
services:
  nginx-base:
    image: nginx:1.19-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certs/:/etc/nginx/ssl
  redis-base:
    image: redis:alpine
    hostname: redis
    ports:
      - '${REDIS_IO_PORT}:${REDIS_IO_PORT}'
    command:
      - /bin/sh
      - -c
      - redis-server /usr/local/etc/redis/redis.conf --requirepass "${IO_PASS_STR}"
    volumes:
      - $PWD/.docker/redis/redis-io.conf:/usr/local/etc/redis/redis.conf
    restart: always
  redis-db-base:
    image: redis/redis-stack-server:latest
    hostname: redis-db
    environment:
      - REDIS_ARGS='--requirepass ${DB_PASS_STR}'
    command: >
      redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - $PWD/.docker/redis/redis-db.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '${REDIS_DB_PORT}:${REDIS_DB_PORT}'
    restart: always
