version: '3.7'
services:
  nginx-base:
    image: nginx:1.19-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certs/:/etc/nginx/ssl
  redis-base:
    image: redis:alpine
    hostname: redis
    ports:
      - '${REDIS_IO_PORT}:${REDIS_IO_PORT}'
    restart: always
  redis-db-base:
    image: redislabs/rejson
    hostname: redis-redisjson
    ports:
      - '${REDIS_DB_PORT}:${REDIS_DB_PORT}'
    command: >
      redis-server /usr/local/etc/redis/redis.conf 
      --loadmodule /usr/lib/redis/modules/rejson.so
    volumes:
      - $PWD/.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
