version: '3.7'
services:
  chat-backend:
    build:
      context: ./
      dockerfile: ./apps/chat-backend/Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - 'redis'
  chat-frontend:
    build:
      context: ./
      dockerfile: ./apps/chat-frontend/Dockerfile
    ports:
      - '4200:4200'
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - '6379:6379'
    restart: always
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 443:443
    volumes:
      - ./certs/:/etc/nginx/ssl
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
