version: '3.7'
services:
  redis:
    extends:
      file: common-services.yml
      service: redis-base
  redis-db:
    extends:
      file: common-services.yml
      service: redis-db-base
  nginx:
    extends:
      file: common-services.yml
      service: nginx-base
  chat-backend:
    build:
      context: .
      dockerfile: ./apps/chat-backend/Dockerfile
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    depends_on:
      - 'redis'
      - 'redis-db'
      - 'nginx'
