version: '3.7'
services:
  chat-backend:
    build:
      context: ./
      dockerfile: ./apps/chat-backend/Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: always
  url-shortner:
    image: shlinkio/shlink:stable
    ports:
      - '8080:8080'
    env_file: ./.env
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 443:443
    volumes:
      - ./certs/:/etc/nginx/ssl
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
