version: '3.7'
services:
  chatserver:
    build:
      context: ./
      dockerfile: ./apps/chat-backend/Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
  nginx:
    build:
      context: .
    restart: always
    image: nginx:1.19-alpine
    ports:
      - '80:80'
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
