[package]
name = "key-protector-passphrase"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
argon2.workspace = true
aws-lc-rs.workspace = true
session-storage = { version = "=0.1.0", path = "../session-storage" }
thiserror.workspace = true
zeroize.workspace = true

[lints]
workspace = true
