name: CI Job

permissions:
  pull-requests: write
  repository-projects: write
  contents: write

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches:
      - master
jobs:
  eslint_linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js lint
  prettier_linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node common/scripts/install-run-rush.js prettier
  pr_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js test:ci
  automerge:
    runs-on: ubuntu-latest
    needs: [dependabot-update]
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  dependabot-update:
    runs-on: ubuntu-latest
    needs: [eslint_linter_job, prettier_linter_job, pr_job]
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          node-version: 14
      - name: Update Lock File
        run: node common/scripts/install-run-rush.js update
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          message: 'Updated project dependencies'
          default_author: github_actions
